apiVersion: v1
kind: ConfigMap
metadata:
  name: web-configmap
  namespace: three-tier-app-ns
data:
  api_connection_url: api-service

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configmap
  namespace: three-tier-app-ns
data:
  database_connection_url: database-service 

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque # "Opaque" - default for arbitrary key-value pairs
data:
  # Generate value for each key below with this command "echo -n '{value}' | base64"
  username: {Generated value from the comment about}
  password: {Generated value from the comment about}