apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: web-hpa
  namespace: three-tier-app-ns
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: web-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  #targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: api-hpa
  namespace: three-tier-app-ns
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
    #targetCPUUtilizationPercentage: 50